config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  post '/admins.:id' => 'users#change_admin_status'
  post 'choose_date' => 'pairs#choose_date', as: :choose_date

  devise_for :admins
  devise_for :users

  resources :pairs
  resources :profiles
  resources :admins, only: [:index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pair.rb
class Pair < ApplicationRecord
  belongs_to :student_one, class_name: User
  belongs_to :student_two, class_name: User
  validates_presence_of :student_one, :student_two

  @students_half_1, @students_half_2 = User.all.each_slice( (User.all.count/2.0).round ).to_a

  def self.daily_rotation
    x=@students_half_1.pop
    @students_half_2.push(x)
    y=@students_half_2.shift
    @students_half_1.insert(1,y)
  end

  
  def self.show_today
    Pair.where(:pair_date == Date.today)
  end

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :profile_picture, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile, dependent: :destroy

  def has_profile?
    profile.present?
  end

  def full_name
    profile.full_name
  end

  def is_admin?
    admin == true
  end

  def change_admin_status
    self.admin = !self.admin
    self.save
  end

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!
  def home
  end
end

app/controllers/pairs_controller.rb
class PairsController < ApplicationController
  before_action :authenticate_user!
  before_action :must_be_admin, only: :index
  helper_method :rotate_and_generate_new

  def index
    @pairs = Pair.all
    @my_pairs1 = Pair.where(student_one_id: current_user.id)
    @my_pairs2 = Pair.where(student_two_id: current_user.id)
    @users = User.all
    @students_half_1, @students_half_2 = @users.each_slice( (@users.count/2.0).round ).to_a
  end

  def choose_date

    @users = User.all
    @students_half_1, @students_half_2 = @users.each_slice( (@users.count/2.0).round ).to_a
    Pair.daily_rotation
    total_of_pairs = (User.count % 2 == 0) ? (User.count / 2) : (User.count / 2 + 1)
    (0...total_of_pairs).each do |index_of_pair|
    @pair = Pair.create(student_one: @students_half_1[index_of_pair], student_two: @students_half_2[index_of_pair], pair_date: params[:chosen_date] )

  end
  end


  def new
    @pair = Pair.new
  end

  def create
    @pair = Pair.new
    @pair.save
  end

  def destroy
    @pair.destroy
  end

  def show
    @pair = Pair.find_by(student_one_id: current_user.id) || @pair = Pair.find_by(student_two_id: current_user.id)
  end

  def update
    @pair = Pair.find(params[:id])
    @pair.update(pair_params)
    @pair.save
  end




  private

  def must_be_admin
    unless current_user && current_user.admin?
      redirect_to root_path, notice: "Only admin can view all pairs"
    end
  end

  def pair_params
    params.require(:pair).permit(:student_one, :student_two, :pair_date)
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:edit, :update]
  before_action :authenticate_user!

  def new
    @profile = Profile.new
  end

  def create
    @profile = current_user.build_profile(profile_params)

    if @profile.save
      redirect_to root_path(@profile), notice: "Hi #{@profile.first_name}, you have successfully created your profile!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @profile.update(profile_params)
      redirect_to edit_profile_path(@profile), notice: "Hi #{@profile.first_name}, you have successfully updated your profile!"
    else
      render :edit
    end
  end

  private
    def set_profile
      @profile = current_user.profile
    end

    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :profile_picture)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def change_admin_status
    @user = User.find(params[:id])
    @user.change_admin_status

    respond_to do |format|
      format.html { redirect_to admins_path }
      format.json { render json: @user }
    end
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pairs_helper.rb
module PairsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/index.html.erb
<div class="container">

  <h1>Hi Admin</h1>

  <hr>

  <ul>
    <p>Admins</p>
    <% @users.each do |user| %>
      <% unless !user.is_admin? || user == current_user %>
        <li><%= user.email %>
        <%= link_to "[demote]", admins_path(user.id), remote: true, method: :post %></li>
      <% end %>
    <% end %>
    <hr>
    <p>Users</p>
    <% @users.each do |user| %>
      <% unless user.is_admin? || user == current_user %>
        <li><%= user.email %>
        <%= link_to "[make admin]", admins_path(user.id), remote: true, method: :post %></li>
      <% end %>
    <% end %>
  </ul>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UltimateTeams</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  </body>
    <%= render "shared/navbar" %>
    
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <p>hello world </p>
</div>

app/views/pairs/index.html.erb
<div class="container">
  <h1>Today's Teams:</h1>

  <div>
    <%= form_tag(choose_date_path, :method=>'post') do %>
      <p><%= date_field_tag :chosen_date %></p>
      <p><%= submit_tag 'Generate new pairs' %></p>
    <% end %>

  </div>


    <p><% @pairs.each do |pair| %>

      <%= "Student 1: #{pair.student_one.email} -- Student 2: #{pair.student_two.email} --- #{pair.pair_date}" %></p>
  <% end %>
</div>



<div class="container">
  <% @my_pairs1.each do |pair| %>
    <%= "#{pair.student_one.email} -- #{pair.student_two.email}" %>
  <% end %>
  <% @my_pairs2.each do |pair| %>
    <%= "#{pair.student_one.email} -- #{pair.student_two.email}" %>
  <% end %>

</div>

app/views/pairs/show.html.erb
<div class="show_team_mate">
  <div class="container">
    <h1><%= "Hi #{current_user.has_profile? ? current_user.full_name : current_user.email}!"  %></h1>
    <%= "Your team mate for today will be:"  %>
    <strong><% if current_user == @pair.student_one %>
      <%= "#{@pair.student_two.has_profile? ? @pair.student_two.full_name : @pair.student_two.email}" %>
    <% else %>
      <%= "#{@pair.student_one.has_profile? ? @pair.student_one.full_name : @pair.student_one.email}" %>
    <% end %></strong>
  </div>

  <div class="container">
    <div class="profile_picture">
      <%= @pair.student_one.has_profile? ? image_tag(@pair.student_one.profile.profile_picture) : image_tag("https://goo.gl/TiWzUR") %>
      <%= image_tag("https://goo.gl/X4dtFs") %>
      <%= @pair.student_two.has_profile? ? image_tag(@pair.student_two.profile.profile_picture) : image_tag("https://goo.gl/TiWzUR") %>
    </div>
    <div class="container">
      <% unless current_user.has_profile? %>
        <%= "Please create a profile, and upload a recognizable picture of yourself!" %>
      <% end %>
    </div>
  </div>
</div>

<div class="container">
  <% @pairs.each do |pair| %>
    <%= "#{pair.student_one.email} -- #{pair.student_two.email}" %>
  <% end %>
</div>

app/views/profiles/_form.html.erb
<%= form_for @profile do |f| %>
  <% @profile.errors.full_messages.each do |msg| %>
    <p class="alert alert-danger"><%= msg %></p>
  <% end %>

  <div class="form-group">
    <label>First Name</label>
    <%= f.text_field :first_name, placeholder: "First Name", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Last Name</label>
    <%= f.text_field :last_name, placeholder: "Last Name", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Profile Picture</label>
    <%= f.text_field :profile_picture, placeholder: "Image URL", class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
    <%= link_to "Back", root_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    Edit your profile
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    Create your profile
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Ultimate Teams</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">

        <% if !user_signed_in? %>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Log In</a>

          <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
            <li><a href="#"><%= link_to "Log In", new_user_session_path %></a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#"><li><%= link_to "Sign Up", new_user_registration_path %></a></li>
          </ul>
        </li>

        <% elsif current_user.is_admin? %>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.has_profile? ? current_user.full_name : current_user.email %></a>

          <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
            <li><%= link_to "View Users", admins_path %></li>
            <li><%= link_to "View Teams", pairs_path %></li>
            <li role="separator" class="divider"></li>
            <% if current_user.has_profile? %>
              <li><a href="#"><%= link_to "Edit Profile", edit_profile_path(current_user.profile) %></a></li>
              <% else %>
              <li><a href="#"><%= link_to "Create Profile", new_profile_path %></a></li>
              <% end %>
              <li><%= link_to "Change Password", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>

        <% else %>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.has_profile? ? current_user.full_name : current_user.email %></a>

          <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
            <li><%= link_to "Today's Teammate", pair_path(current_user) %></li>
            <li role="separator" class="divider"></li>
            <% if current_user.has_profile? %>
              <li><a href="#"><%= link_to "Edit Profile", edit_profile_path(current_user.profile) %></a></li>
              <% else %>
              <li><a href="#"><%= link_to "Create Profile", new_profile_path %></a></li>
              <% end %>
              <li><%= link_to "Change Password", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>

        <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>